name: 'add label customer submission'

on:
  issues:
    types:
      - opened

permissions:
  issues: write
  pull-requests: write

jobs:
  add-customer-submission-label:
    name: Add customer-submission label
    runs-on: ubuntu-latest
    steps:
      - name: Add customer-submission label
        if: ${{ env.SENZING_MEMBER == 'false' }}
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "customer-submission"
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_MEMBERSHIP_TOKEN }}
          SENZING_MEMBER: ${{ contains( secrets.SENZING_MEMBERS, github.actor ) }}
