name: 'lint workflows'

on:
  push:
    branches-ignore: [main]
    paths:
      - .github/**
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/**

jobs:
  lint-code-base:
    permissions:
      contents: read
      packages: read
      statuses: write
    uses: senzing-factory/build-resources/.github/workflows/linter.yaml@main
    with:
      filter-regex-include: ".*.github/workflows/.*"
      # temp for initial full test
      validate-all-codebase: true
