name: 'lint workflows'

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

jobs:
  lint-workflows:
    uses: senzing-factory/build-resources/.github/workflows/lint-workflows.yaml@linter-test
